### ISSUE TITLE
news_admin.php

### ISSUE THREAD

**Issue by helmuthm** [php-fusion/ci-News#6]
is this correct:

`$locale['601'] = "Thumb size:";
$locale['602'] = "Photo size:";
$locale['603'] = "Maximum photo size:";
$locale['604'] = "Width x Height";
$locale['605'] = "Maximum file size (bytes):";
$locale['950'] = "Image Upload";
$locale['951'] = "Image link:";
$locale['953'] = "News Item";
$locale['954'] = "Thumb ratio:";
$locale['955'] = "Original";
$locale['956'] = "Square";
$locale['957'] = "Image on Front-page";
$locale['958'] = "Image on Read-more";
$locale['959'] = "Uploaded Photo";
$locale['news_submit'] = "%s News";`

should it not be:

`$locale['news_s601'] = "Thumb size:";
$locale['news_s602'] = "Photo size:";
$locale['news_s603'] = "Maximum photo size:";
$locale['news_s604'] = "Width x Height";
$locale['news_s605'] = "Maximum file size (bytes):";
$locale['news_s950'] = "Image Upload";
$locale['news_s951'] = "Image link:";
$locale['news_s953'] = "News Item";
$locale['news_s954'] = "Thumb ratio:";
$locale['news_s955'] = "Original";
$locale['news_s956'] = "Square";
$locale['news_s957'] = "Image on Front-page";
$locale['news_s958'] = "Image on Read-more";
$locale['news_s959'] = "Uploaded Photo";
$locale['news_submit'] = "%s News";`

??????????????????

**Comment by RobiNN1** [comment]
Yes, I'll fix it tomorrow.

**Comment by RobiNN1** [comment]
I need check all infusion and add missing locale prefix
